// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7B5LhmvmnHWVTCRjh8LuxWMzf7IAVWFU',
    appId: '1:450877646956:web:04fe5f695a2ed199ec5049',
    messagingSenderId: '450877646956',
    projectId: 'project-app-e17ad',
    authDomain: 'project-app-e17ad.firebaseapp.com',
    storageBucket: 'project-app-e17ad.appspot.com',
    measurementId: 'G-RFX1567SWL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyArNBviKWW7JODIT-U9DhSNok8Y_z4OiXI',
    appId: '1:450877646956:android:2b234e8804ecceb3ec5049',
    messagingSenderId: '450877646956',
    projectId: 'project-app-e17ad',
    storageBucket: 'project-app-e17ad.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSbKcgciLmqRmToXCV5EmoUQ7XN2EvrnE',
    appId: '1:450877646956:ios:b226a45ca4100a6bec5049',
    messagingSenderId: '450877646956',
    projectId: 'project-app-e17ad',
    storageBucket: 'project-app-e17ad.appspot.com',
    iosBundleId: 'com.example.projectAppMidtermFirstHaft',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCSbKcgciLmqRmToXCV5EmoUQ7XN2EvrnE',
    appId: '1:450877646956:ios:e399f3a3ce43d839ec5049',
    messagingSenderId: '450877646956',
    projectId: 'project-app-e17ad',
    storageBucket: 'project-app-e17ad.appspot.com',
    iosBundleId: 'com.example.projectAppMidtermFirstHaft.RunnerTests',
  );
}
